### ISSUE TITLE
F E A T U R E | Interact with MongoDB Database

### ISSUE THREAD

**Issue by LemMem** [LemMem/Incandescence-Legacy#2]
**Is your feature request related to a problem? Please describe.**
Currently, our REST API doesn't do anything. Obviously we wouldn't have a product if it didn't do anything.

**Describe the solution you'd like**
The way each command should behave is described on Solstice's [readme ](https://github.com/LemMem/horizon/blob/dev/solstice/README.md)and the wiki.

**Describe alternatives you've considered**
We could try implementing an SQL database like [PostgreSQL](https://www.postgresql.org/), but that seems a little heavy-duty for a project like this.

**TODO**

- [x] Create Service for Database Requests
- [ ] Use ZeroMQ to connect new service w/ Solstice
- [ ] Connect to the Database to begin making requests
- [ ] Read and Write to database appropriately for commands.
