### ISSUE TITLE
F E A T U R E | Sunrise Map Hub

### ISSUE THREAD

**Issue by LemMem** [LemMem/Incandescence-Legacy#6]
**Is your feature request related to a problem? Please describe.**
There should be an easy way to get information about maps in the Incan ecosystem. Creating a set of pages related to maps should create a concise way to get information, and is simpler than having a bot command (Although I would not be opposed to adding that later)

**Describe the solution you'd like**
A set of pages for every map in Incan, with relevant information like:
- The map's maker
- Images of the map
- Guides for the map
- A brief summary of the map
- External Resources on the map (I.E. comp.tf pages)

**TODO**
- [ ] Map Hub home page (tiles w/ all the maps)
- [ ] Individual Map pages based on Markdown files
- [ ] Write Markdown files for 7 planned maps
